version: '3.9'

services:
  backend:
    container_name: planning
    build: 
      context: ./backend
      target: development
    command: npm run start:dev
    ports: 
      - 3000:3000
    env_file: 
      - ./backend/.env
    depends_on: 
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: valcoop
      MYSQL_USER: planning
      MYSQL_PASSWORD: mysqlpassword
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
