CREATE DATABASE IF NOT EXISTS valcoop;

USE valcoop;

CREATE TABLE jobs (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  color VARCHAR(100) NOT NULL,
  isDeleted BOOLEAN NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  externalID VARCHAR(100) NOT NULL,
  fullName VARCHAR(100) NOT NULL,
  phoneNumber VARCHAR(20),
  isAdmin BOOLEAN NOT NULL,
  token TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `absence_types` (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  reason VARCHAR(200) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `user_slots_absences` (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userID INT NOT NULL,
  absenceTypeID INT NOT NULL,
  description VARCHAR(200),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (absenceTypeID) REFERENCES `absence_types`(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE slots (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  active BOOLEAN NOT NULL,
  userAdminCreated INT NOT NULL,
  lastUserAdminUpdated INT NOT NULL,
  startDate DATETIME NOT NULL,
  duration INT NOT NULL,
  jobID INT NOT NULL,
  totalPlace INT NOT NULL,
  isDeleted BOOLEAN NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userAdminCreated) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (lastUserAdminUpdated) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (jobID) REFERENCES jobs(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `user_slots` (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userID INT NOT NULL,
  slotID INT NOT NULL,
  startDate DATETIME NOT NULL,
  done BOOLEAN NOT NULL,
  userSlotAbsenceID INT,
  isDeleted BOOLEAN NOT NULL,
  fullName VARCHAR(200) NOT NULL,
  phoneNumber VARCHAR(20) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (slotID) REFERENCES slots(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (userSlotAbsenceID) REFERENCES `user_slots_absences`(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

INSERT INTO `absence_types` (reason) VALUE ('Autres');